const openListCleaner = (openList) => {
  return new Promise((resolve) => {
    resolve(
      openList.map((obj) => {
        const reObj = {
          "id": obj.id,
          "CounselorProfile": obj.CounselorProfile,
          "startDate": obj.Open.startDate,
          "endDate": obj.Open.endDate,
          "Open": {
            "MON9": obj.Open.MON9,
            "MON10": obj.Open.MON10,
            "MON11": obj.Open.MON11,
            "MON12": obj.Open.MON12,
            "MON13": obj.Open.MON13,
            "MON14": obj.Open.MON14,
            "MON15": obj.Open.MON15,
            "MON16": obj.Open.MON16,
            "MON17": obj.Open.MON17,
            "MON18": obj.Open.MON18,
            "TUE9": obj.Open.TUE9,
            "TUE10": obj.Open.TUE10,
            "TUE11": obj.Open.TUE11,
            "TUE12": obj.Open.TUE12,
            "TUE13": obj.Open.TUE13,
            "TUE14": obj.Open.TUE14,
            "TUE15": obj.Open.TUE15,
            "TUE16": obj.Open.TUE16,
            "TUE17": obj.Open.TUE17,
            "TUE18": obj.Open.TUE18,
            "WED9": obj.Open.WED9,
            "WED10": obj.Open.WED10,
            "WED11": obj.Open.WED11,
            "WED12": obj.Open.WED12,
            "WED13": obj.Open.WED13,
            "WED14": obj.Open.WED14,
            "WED15": obj.Open.WED15,
            "WED16": obj.Open.WED16,
            "WED17": obj.Open.WED17,
            "WED18": obj.Open.WED18,
            "THU9": obj.Open.THU9,
            "THU10": obj.Open.THU10,
            "THU11": obj.Open.THU11,
            "THU12": obj.Open.THU12,
            "THU13": obj.Open.THU13,
            "THU14": obj.Open.THU14,
            "THU15": obj.Open.THU15,
            "THU16": obj.Open.THU16,
            "THU17": obj.Open.THU17,
            "THU18": obj.Open.THU18,
            "FRI9": obj.Open.FRI9,
            "FRI10": obj.Open.FRI10,
            "FRI11": obj.Open.FRI11,
            "FRI12": obj.Open.FRI12,
            "FRI13": obj.Open.FRI13,
            "FRI14": obj.Open.FRI14,
            "FRI15": obj.Open.FRI15,
            "FRI16": obj.Open.FRI16,
            "FRI17": obj.Open.FRI17,
            "FRI18": obj.Open.FRI18,
            "SAT9": obj.Open.SAT9,
            "SAT10": obj.Open.SAT10,
            "SAT11": obj.Open.SAT11,
            "SAT12": obj.Open.SAT12,
            "SAT13": obj.Open.SAT13,
            "SAT14": obj.Open.SAT14,
            "SAT15": obj.Open.SAT15,
            "SAT16": obj.Open.SAT16,
            "SAT17": obj.Open.SAT17,
            "SAT18": obj.Open.SAT18,
            "SUN9": obj.Open.SUN9,
            "SUN10": obj.Open.SUN10,
            "SUN11": obj.Open.SUN11,
            "SUN12": obj.Open.SUN12,
            "SUN13": obj.Open.SUN13,
            "SUN14": obj.Open.SUN14,
            "SUN15": obj.Open.SUN15,
            "SUN16": obj.Open.SUN16,
            "SUN17": obj.Open.SUN17,
            "SUN18": obj.Open.SUN18
          }
        };
        
        return reObj;
      })
    )  
  })
};

module.exports = openListCleaner;

/*
{
  "success": true,
  "openList": [
    {
      "id": 2,
      "CounselorProfile": {
        "name": "상담사01"
      },
      "Open": {
        "startDate": "2019-01-01",
        "endDate": null,
        "MON9": false,
        "MON10": false,
        "MON11": false,
        "MON12": false,
        "MON13": false,
        "MON14": false,
        "MON15": false,
        "MON16": false,
        "MON17": false,
        "MON18": false,
        "TUE9": false,
        "TUE10": false,
        "TUE11": false,
        "TUE12": false,
        "TUE13": false,
        "TUE14": false,
        "TUE15": false,
        "TUE16": false,
        "TUE17": false,
        "TUE18": false,
        "WED9": false,
        "WED10": false,
        "WED11": false,
        "WED12": false,
        "WED13": false,
        "WED14": false,
        "WED15": false,
        "WED16": false,
        "WED17": false,
        "WED18": false,
        "THU9": false,
        "THU10": false,
        "THU11": false,
        "THU12": false,
        "THU13": false,
        "THU14": false,
        "THU15": false,
        "THU16": false,
        "THU17": false,
        "THU18": false,
        "FRI9": false,
        "FRI10": false,
        "FRI11": false,
        "FRI12": false,
        "FRI13": false,
        "FRI14": false,
        "FRI15": false,
        "FRI16": false,
        "FRI17": false,
        "FRI18": false,
        "SAT9": false,
        "SAT10": false,
        "SAT11": false,
        "SAT12": false,
        "SAT13": false,
        "SAT14": false,
        "SAT15": false,
        "SAT16": false,
        "SAT17": false,
        "SAT18": false,
        "SUN9": false,
        "SUN10": false,
        "SUN11": false,
        "SUN12": false,
        "SUN13": false,
        "SUN14": false,
        "SUN15": false,
        "SUN16": false,
        "SUN17": false,
        "SUN18": false
      }
    },
    {
      "id": 3,
      "CounselorProfile": {
        "name": "상담사02"
      },
      "Open": {
        "startDate": "2019-01-01",
        "endDate": "2019-12-31",
        "MON9": false,
        "MON10": false,
        "MON11": false,
        "MON12": false,
        "MON13": false,
        "MON14": false,
        "MON15": false,
        "MON16": false,
        "MON17": false,
        "MON18": false,
        "TUE9": false,
        "TUE10": false,
        "TUE11": false,
        "TUE12": false,
        "TUE13": false,
        "TUE14": false,
        "TUE15": false,
        "TUE16": false,
        "TUE17": false,
        "TUE18": false,
        "WED9": false,
        "WED10": false,
        "WED11": false,
        "WED12": false,
        "WED13": false,
        "WED14": false,
        "WED15": false,
        "WED16": false,
        "WED17": false,
        "WED18": false,
        "THU9": false,
        "THU10": false,
        "THU11": false,
        "THU12": false,
        "THU13": false,
        "THU14": false,
        "THU15": false,
        "THU16": false,
        "THU17": false,
        "THU18": false,
        "FRI9": false,
        "FRI10": false,
        "FRI11": false,
        "FRI12": false,
        "FRI13": false,
        "FRI14": false,
        "FRI15": false,
        "FRI16": false,
        "FRI17": false,
        "FRI18": false,
        "SAT9": false,
        "SAT10": false,
        "SAT11": false,
        "SAT12": false,
        "SAT13": false,
        "SAT14": false,
        "SAT15": false,
        "SAT16": false,
        "SAT17": false,
        "SAT18": false,
        "SUN9": false,
        "SUN10": false,
        "SUN11": false,
        "SUN12": false,
        "SUN13": false,
        "SUN14": false,
        "SUN15": false,
        "SUN16": false,
        "SUN17": false,
        "SUN18": false
      }
    }
  ]
}
*/